name: Release Creation
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get package version
        id: package-version
        uses: koj-co/package-version-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update GitHub Release
        uses: tubone24/update_release@v1.1.0
        with:
          release_name: Release ${{ steps.package-version.outputs.package-version }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.package-version.outputs.package-version }}
    outputs:
      version:  ${{ steps.package-version.outputs.package-version }}

  build:
    name: Build the app
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Building using tag version
        run: |-
          echo "Building the app..."
          echo "Docker image creation using the version: ${{ needs.release.outputs.version }}"