name: Tag for Release Creation
on:
  push:
    branches:
      - dev

jobs:
  tag:
    name: Application Tagging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name:  Automated Github Action Version Bump
        id: version_bump
        uses:  'rimonhanna/gh-action-bump-version@master'

      - name: Getting the raw version
        id: version
        run: |-
          echo ::set-output name=RAW_VERSION::$(echo ${{steps.version_bump.outputs.TAG}} | cut -d 'v' -f 2)
          echo ::set-output name=VERSION::$(echo ${{steps.version_bump.outputs.TAG}})
          echo ::set-output name=TAG::$( [ ${{ contains(github.ref, 'dev') }} ] && echo '-dev' || echo '' )

    outputs:
      version: ${{ steps.version.outputs.VERSION }}${{ steps.version.outputs.TAG }}

  build:
    name: Build the app
    runs-on: ubuntu-latest
    needs: tag
    if: ${{ contains(needs.tag.outputs.version, 'dev') }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get the version
        id: get_version
        run: |-
          echo ::set-output name=VERSION::${{ needs.tag.outputs.version }}

      - name: Building using tag version
        run: |-
          echo "Building the app..."
          echo "Docker image creation using the version: ${{ steps.get_version.outputs.VERSION }}"