name: Tag for Release Creation
on:
  push:
    branches:
      - main
      - dev

jobs:
  tag:
    name: Application Tagging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name:  Automated Github Action Version Bump
        id: version_bump
        uses:  'rimonhanna/gh-action-bump-version@master'

      - name: Getting the raw version
        id: version
        run: |-
          echo ::set-output name=RAW_VERSION::$(echo ${{steps.version_bump.outputs.TAG}} | cut -d 'v' -f 2)
          echo ::set-output name=VERSION::$(echo ${{steps.version_bump.outputs.TAG}})
          echo ::set-output name=TAG::$( [ ${{ contains(github.ref, 'dev') }} ] && echo '.UNSTABLE' || echo '' )

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}${{ steps.version.outputs.TAG }}
          release_name: Release ${{ steps.version.outputs.VERSION }}${{ steps.version.outputs.TAG }}
          draft: false
          prerelease: ${{ !contains(github.ref, 'main') }}
          body_path: ./CHANGELOG.md
    outputs:
      version: ${{ steps.composer.outputs.version }}