name: Tag new version
on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  tag:
    name: Application Tagging
    runs-on: ubuntu-latest
    if: "!(github.event_name == 'pull_request' && !github.event.pull_request.merged)"
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Bump version on merging Pull Requests with specific labels. (bump:major,bump:minor,bump:patch)
      - name: Version Calculation
        if: github.event.pull_request.merged
        id: version-calc
        uses: haya14busa/action-bumpr@v1
        with:
          dry_run: true
          default_bump_level: patch

      - name: Cofiguring Git
        run: |-
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Change version
        run: |-
          npm version ${{ steps.version-calc.outputs.next_version }} --git-tag-version=true
          git push gh-origin ${{ steps.version-calc.outputs.next_version }}
